###############################
#  Binaries                   #
###############################
brew "mas"
###############################
#  Cask                       #
###############################
cask "arc"
cask "rectangle"
cask "sourcetree"
cask "warp"
cask "monitorcontrol"
###############################
#  mas                        #
###############################
mas "rcmd", id: 1596283165
mas "LINE", id: 539883307
mas "Kindle", id: 302584613